### PR TITLE
Support template files without an extension

### PR DESCRIPTION
**Pull request by adamhjk**
Currently, mustache looks for files in the following order:
- If there is an extension on the file, use it directly
- If there is no extension on the file, use .mustache

This patch extends the behavior to be:
- If there is an extension on the file, use it directly
- If there is no extension on the file, look for .mustache
- If neither of those exist, look for the file without any extension

### CODE REVIEW

**Comment by adamhjk** [comment]
I'll re-open this in a minute - a bit premature :)

**Comment by adamhjk** [comment]
Ok - false alarm. Should be gtg. :)

**Comment by Ryman** [comment]
I'm wondering if this makes more sense to add to the top-level `compile_path` instead, where the other fallback/magic is currently?

With this change, there could be some files with `.foo` extension and some partials that are extension-less, I don't think it should be encouraged to have both in the same set of files? But, if the parent file is without an extension then it should be totally fine to go ahead with all files being extensionless (so changing around like 137 in old revision would handle this)

Also, this code is a member of `Context`, where the user could just initialise the context with `template_extension: "".to_string()`? Whereas the top-level `compile_*` functions are very much for convenience as I understand it. (Note, I didn't design this specific api,  this is just my opinions on it :smile_cat: )

**Comment by adamhjk** [comment]
I'm totally open to whatever implementation makes sense. If the right thing is for me to just forego the existing code and initialize a context myself, I can do that. Happy to move it elsewhere as well. Y'all tell me, and I'll do it.

Thanks for looking!

**Comment by Ryman** [comment]
Initializing a context yourself would definitely let you do what you want to do, but if we want to make it easier for other users then I think we should adjust the logic in the top-level `compile_path`.

I would suggest that before doing `unwrap_or("mustache")`, we do an existence check via [is_file](http://doc.rust-lang.org/std/fs/struct.Metadata.html#method.is_file) for an extension-less file, and if one is found we use that, otherwise we default to "mustache". That way if the user has got 2 files `foo` and `foo.mustache` they can be more explicit in their inputs to get the `foo.mustache` while still allowing extension-less files to be used and allowing people to be lazy and dropping the verbose `.mustache` in the general case.

Also, it would be worth adding a testcase for this scenario, using some copies of the files in [here](https://github.com/nickel-org/rust-mustache/tree/master/src/test-data), ensureing that the correct files are rendered etc and fallback behaviour is working.

**Comment by adamhjk** [comment]
The problem with is_file is that it is currently marked unstable - so using it requires stable rust. Otherwise, I totally agree with you.

**Comment by adamhjk** [comment]
er, using it requires us to force everyone to use unstable rust.

**Comment by Ryman** [comment]
The one I linked to is [stable](http://doc.rust-lang.org/src/std/fs.rs.html#513), you can see an example of use [here](https://github.com/nickel-org/nickel.rs/blob/master/src/static_files_handler.rs#L63-L64)

**Comment by adamhjk** [comment]
Oh awesome. I'll send another PR.

**Comment by Ryman** [comment]
You can use `git commit --amend` and `git push -f ..` and GitHub will update the PR, unless you want both open as a comparison. Just mentioning incase you are not aware :)

**Comment by Ryman** [comment]
@adamhjk Any update on this?

**Comment by adamhjk** [comment]
Only that I got distracted and haven't had a chance to finish it up, since
my local branch was 'working for me'. :) I'll get to this this week, if
that's cool - of course, I won't cry if it gets done without me.

**Comment by Ryman** [comment]
Closing this for now, happy to take another look at it in future if someone wants to take another shot at this. Dear future reader, the changes required are something along the lines of https://github.com/nickel-org/rust-mustache/pull/16#issuecomment-110754232 and to add some tests so we don't regress in future.

**Pull request closed without merging**
