### PR TITLE
Switch to serde (Rebase of #52)

### PR DESCRIPTION
**Pull request by Ryman**
This is a rebase of #52.

### CODE REVIEW

**Comment by Ryman** [comment]
Expecting travis to fail unless https://github.com/budziq/rust-skeptic/pull/71 is merged (fails locally for me). If it's not then we could skip the readme tests for older compiler versions or something as an easy workaround.

**Comment by Kerollmops** [comment]
Can't we just remove `1.16.0` from the `travise.yml` file for a moment ? Accept this PR and work on skeptic after ?

The actual blocking compilation is about a [shorthand structure argument](https://rustbyexample.com/custom_types/structs.html) feature that is not stable on `1.16.0`. Do we really need to be valid for this version ?

**Comment by Ryman** [comment]
@Kerollmops Yeah, totally! I just lost track of the PR since noone else commented :( I've redone the skeptic commit to just test the readme on the nightly compiler for now (can't optionally use skeptic as a build dependency because cargo doesn't support optional build/dev deps)

Let's see what Travis says about this!

**Comment by Ryman** [comment]
Messed a little with the history to put the version bump at the end: Merged as https://github.com/nickel-org/rust-mustache/compare/b1876caaf8c2b0d0fa9200b61a12e21bc0db58af...bdae578822d1f2216e5021686bbd4c2173d61976

Published as [0.9.0](https://crates.io/crates/mustache/0.9.0), sorry it took so long! 🥂

**Pull request closed without merging**
