### PR TITLE
WIP: updates for Rust 1.0.0-alpha

### PR DESCRIPTION
**Pull request by rgs1**
This is not finished! Mostly WIP, not fully working but it builds. Will follow-up tomorrow. 

Signed-off-by: Raul Gutierrez S <rgs@itevenworks.net>

### CODE REVIEW

**Comment by SimonPersson** [comment]
Briliant! I'll take a look at making the other dependencies build and hopefully we can have nickel working again by tomorrow.

**Comment by rgs1** [comment]
what's still broken (and commented) is:

```
pub enum Data<'a> {
   ...,
  Fun(Box<FnMut.. >),
}
```
I replaced the RefCell<closure> with Box<FnMut>, but that has problems with mutability, so I need to find a workaround for that.

**Comment by rgs1** [comment]
Ok, updated! Now it builds entirely without commenting anything. Now I need to fix the tests!

**Comment by rgs1** [comment]
So tests mostly pass now:

```
failures:
    template::tests::test_spec_comments
    template::tests::test_spec_delimiters
    template::tests::test_spec_interpolation
    template::tests::test_spec_inverted
    template::tests::test_spec_lambdas
    template::tests::test_spec_partials
    template::tests::test_spec_sections

test result: FAILED. 16 passed; 7 failed; 0 ignored; 0 measured
```

The spec ones are missing this file:

```
spec/specs/inverted.json
```

which seems to be missing in the repo? There are some style issues with the commit, but we are almost there!

**Comment by rgs1** [comment]
Oh, I missed the spec/ is a submodule. Now more things pass:

```
cargo test
     Running ../target/mustache-70788c051df1fb53

running 23 tests
test builder::tests::test_empty_builders ... ok
test builder::tests::test_map_fn_builder ... ok
test builder::tests::test_builders ... ok
test compiler::tests::test_compile_delimiters ... ok
test compiler::tests::test_compile_etags ... ok
test builder::tests::test_vec_fn_builder ... ok
test compiler::tests::test_compile_texts ... ok
test compiler::tests::test_compile_sections ... ok
test compiler::tests::test_compile_partials ... ok
test template::tests::test_render_etags ... ok
test compiler::tests::test_compile_utags ... ok
test template::tests::test_render_sections ... ok
test template::tests::test_render_inverted_sections ... ok
test template::tests::test_render_utags ... ok
test template::tests::test_render_texts ... ok
test template::tests::test_render_partial ... ok
test template::tests::test_spec_comments ... ok
test template::tests::test_spec_delimiters ... ok
test template::tests::test_spec_inverted ... ok
test template::tests::test_spec_lambdas ... ok
test template::tests::test_spec_interpolation ... ok
test template::tests::test_spec_partials ... ok
test template::tests::test_spec_sections ... ok

test result: ok. 23 passed; 0 failed; 0 ignored; 0 measured
   Doc-tests mustache

running 12 tests
test builder::insert_fn_0 ... FAILED
test builder::insert_bool_0 ... ok
test builder::insert_map_0 ... ok
test builder::insert_0 ... ok
test builder::insert_str_0 ... ok
test builder::push_fn_0 ... FAILED
test builder::push_bool_0 ... ok
test builder::push_0 ... ok
test builder::insert_vec_0 ... ok
test builder::push_str_0 ... ok
test builder::push_vec_0 ... ok
test builder::push_map_0 ... ok

```

Checking the failures
````

**Comment by rgs1** [comment]
Everything passes now!

```
test result: ok. 23 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests mustache

running 12 tests
test builder::insert_bool_0 ... ok
test builder::insert_fn_0 ... ok
test builder::insert_map_0 ... ok
test builder::insert_0 ... ok
test builder::insert_str_0 ... ok
test builder::push_bool_0 ... ok
test builder::push_0 ... ok
test builder::insert_vec_0 ... ok
test builder::push_str_0 ... ok
test builder::push_fn_0 ... ok
test builder::push_vec_0 ... ok
test builder::push_map_0 ... ok

test result: ok. 12 passed; 0 failed; 0 ignored; 0 measured


Compilation finished at Sun Jan 18 00:18:14
```

Branch updated and ready for merge (modulo some style issues probably).

**Comment by SimonPersson** [comment]
Would you mind getting rid of the warnings too? Most go away with a `#![allow(unstable)]` in lib.rs and the others don't look so hard to get rid of either. It's not a super big deal but it's not a lot of work to get rid of them.

Great job! I've looked into groupable but couldn't get it to work. Perhaps @Ryman has some ideas there?

**Comment by rgs1** [comment]
Sure, I'll get to the warnings and then I'll move to the other deps.

**Comment by SimonPersson** [comment]
Sounds good. I updated all deps from upstream today, the only one that still doesn't build is groupable-rs. I couldn't get it working but maybe you'll have more patience than me!

Thanks for your good work!

**Comment by rgs1** [comment]
@SimonPersson most warnings are gone. There's one remaining about dead code which I think is bogus and the other one about deprecating #derive(Encodable) in favor of #derive(RustcEncodable), which implies using the external rustc-serialize in favor of libserialize. I think we can go with what we have and then revisit these warnings.

I rather focus on groupable-rs now so we can get nickel.rs back on its feet! Let me know what you think.

**Comment by SimonPersson** [comment]
Sounds good to me. I'll merge this and we can revisit those changes later.

**Comment by rgs1** [comment]
Half-way through with groupable-rs: https://github.com/nickel-org/groupable-rs/pull/1

**Pull request merged**
