### PR TITLE
fix(Template): allow rendering boolean values as leafs

### LINKED ISSUE #60: Panic on rendering boolean
This program:

    extern crate mustache;

    use std::io;
    use mustache::MapBuilder;

    fn main() {
        let template = mustache::compile_str("{{ok}}").unwrap();
        let data = MapBuilder::new()
            .insert_bool("ok", true)
            .build();
        template.render_data(&mut io::stdout(), &data).unwrap();
        println!();
    }

fails with the following error:

    thread 'main' panicked at 'bug: render_utag: unexpected value Bool(true).
    Please report this issue on GitHub if you find an input that triggers this case.',
    /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/mustache-0.9.0/src/template.rs:224:25

Instead, I expect it to produce:

    true

My thoughts:

- It would be nice to be able to use booleans in a template like {{ok}} and get 'true' or 'false'.
- Even if booleans can _only_ be used as {{#ok}}...{{/ok}}, this is a poor error message.
- This error occurs in `render_utag`, but why should this be unescaped?

### PR DESCRIPTION
**Pull request by Ryman**
Fixes #60.

### CODE REVIEW

**Comment by nico-abram** [comment]
Is there any reason this hasn't been merged in the past year?

**Comment by rjloura** [comment]
Thanks for fixing.  It would be very helpful to have this merged soon.  Any idea on timeline?

**Comment by cburgdorf** [comment]
@Ryman @erickt Is this still alive?

**Comment by ninjabear** [comment]
Hi all, I feel bad that I've not looked at this. @Ryman's fix looks fine to me but we will need to add it to a release. I think we're prevented doing that until we also solve #63. I will take a look since this is obviously a nuisance!

**Comment by ninjabear** [comment]
This looks fine to me, I've packaged it up in #71, but I think we'll have to find someone to actually publish the crate as this seems to be a manual process that requires creds.

Closing in favour of #71

**Pull request closed without merging**
