### PR TITLE
Fix missing context and data modules

### PR DESCRIPTION
**Pull request by volks73**
I was working on a project where I wanted to use mustache templates and serde, but I could not build the v0.9 serde-enabled branch from @erickt in #52. Similar to @cardoe, I was getting the following error:

```text
error[E0583]: file not found for module `context`
  --> src/lib.rs:13:5
    |
13  | mod context;
```

So, I went about trying to fix the build error as this appeared to be blocking integration of serde and creating a new release (v0.9). I was able to resolve the error related to the `context` module, but then I also received a similar error for the `data` module. I implemented a similar fix for the missing `data` module as well. I am not sure if the ultimate intention was to have `context` and `data` be in separate files from `lib.rs`, but I decided to place them in separate files.

I used the revision before the rebase in #55. Hopefully that does not mess things up for everyone and this will be of use. Thank you.

### CODE REVIEW

**Comment by ninjabear** [comment]
Hey @volks73 thanks for the PR! Will take a look at this and #55 / #52 soon. Lots of ground covered

**Comment by Ryman** [comment]
I've updated #55 which was failing on travis. Is there anything specific this rebase does that is worth highlighting compared to #55? You mention you skipped a commit but I'm not sure which commit you are referring to specifically.

**Comment by volks73** [comment]
>Is there anything specific this rebase does that is worth highlighting compared to #55?

Sorry, it looks like I missed the fixes for the missing `context` and `data` modules in #55, before creating this PR. So, there is nothing worth highlighting in this PR compared to #55, other than this just focuses on fixing the missing modules and does not include any of the other changes in #55. 

It is my understanding that serde support will be added once #55 is merged. Is there something blocking #55 that maybe I can help with?

**Comment by Ryman** [comment]
> Is there something blocking #55 that maybe I can help with?

Giving feedback or any review to the changes is always welcome :) Currently just waiting on a PR to skeptic but if it's delayed/not accepted for too long we can work around that.

**Comment by Ryman** [comment]
Merged https://github.com/nickel-org/rust-mustache/pull/55 which should handle this :) Bug reports welcome!

**Pull request closed without merging**
